# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\fargo\OneDrive\Desktop\New folder\tel.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("border-color: rgb(255, 85, 0);\n"
"gridline-color: rgb(255, 170, 0);\n"
"background-color: rgb(255, 170, 127);")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(140, 20, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(140, 50, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(140, 80, 113, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(140, 110, 113, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 20, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 50, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(30, 80, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(30, 120, 47, 13))
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(10, 170, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.insert)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(100, 170, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.delete)
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(190, 170, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.search)
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(280, 170, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(self.update)

        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(150, 240, 75, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.clicked.connect(self.exit)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "id"))
        self.label_2.setText(_translate("Form", "name"))
        self.label_3.setText(_translate("Form", "family"))
        self.label_4.setText(_translate("Form", "telnumber"))
        self.pushButton.setText(_translate("Form", "insert"))
        self.pushButton_2.setText(_translate("Form", "delete"))
        self.pushButton_3.setText(_translate("Form", "search"))
        self.pushButton_4.setText(_translate("Form", "update"))
        self.pushButton_5.setText(_translate("Form", "exit"))

    def exit(self):
        sys.exit(app.exec_())   

    def insert(self):
        try:
            con = sqlite3.connect("telephon.db") 
            id = (int)(self.lineEdit.text())
            name = self.lineEdit_2.text()
            family = self.lineEdit_3.text()
            telnumber = self.lineEdit_4.text()
            data = [id,name,family,telnumber]
            con.execute("insert into daftartel(id,name,family,telnumber) values(?,?,?,?)",data)
            con.commit()
            print("insert is ok.")
        except Exception as err:
            print(f"Unexpected {err=}")
            print("error in insert.") 
        finally:
            con.close()       
    def delete(self):
        try:
            con = sqlite3.connect("telephon.db") 
            id = (int)(self.lineEdit.text())
            # name=self.lineEdit_2.text()
            # family=self.lineEdit_3.text()
            # telnumber=self.lineEdit_4.text()
            data = [id]
            con.execute("delete from daftartel where id=?",data)
            con.commit()
            print("ok")
        except Exception as err:
            print(f"Unexpected {err=}")
            print("error in delete") 
        finally:
            con.close()  
    def search(self):
        try:
            con = sqlite3.connect("telephon.db") 
            id = (int)(self.lineEdit.text())
            name = self.lineEdit_2.text()
            family = self.lineEdit_3.text()
            # telnumber = self.lineEdit_4.text()

            data = [id]
            data = con.execute("select telnumber from daftartel where id = ?", data)
            for item in data:
                self.lineEdit_4.text = item[0]
                print(item[0])
            con.commit()
            print("ok")
        except Exception as err:
            print(f"Unexpected {err=}")
            print("error in search.") 
        finally:
            con.close()                 
    def update(self):
        try:
            con = sqlite3.connect("telephon.db") 
            id = (int)(self.lineEdit.text())
            name = self.lineEdit_2.text()
            family = self.lineEdit_3.text()
            telnumber = self.lineEdit_4.text()
            data = [telnumber,id]
            con.execute("update daftartel set telnumber=? where (id = ?)", data)
            
            con.commit()
            print("ok")
        except:
            print("error") 
        finally:
            con.close()                        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
